---
ID: "d7d22075-bf7a-45d8-822e-eab9995d0999"
Parent: "857f4d60-19e3-4048-9b6a-4fc001244709"
Template: "857f4d60-19e3-4048-9b6a-4fc001244709"
Path: /sitecore/templates/Project/Hustle/Content Templates/MediaList/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210516T055632Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
