---
ID: "22d414cc-3432-4134-b466-87fae5a44821"
Parent: "6a47e702-eacb-4bf0-afcc-28bcbf82c7e6"
Template: "6a47e702-eacb-4bf0-afcc-28bcbf82c7e6"
Path: /sitecore/templates/Feature/_bookBaseDetails/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210704T124054Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
